name: databricks-import-directory
description: 'Github Action that imports a local directory into the Databricks Workspace'

inputs:
  databricks-host:
    description: 'Databricks host'
    required: true
  databricks-token:
    description: 'Databricks token'
    required: false
  local-path:
    description: 'LOCAL_NOTEBOOKS_PATH'
    required: true
  remote-path:
    description: 'REMOTE_NOTEBOOK_PATH'
    required: true

runs:
  using: "composite"
  steps:
    - id: import-notebooks
      run: | 
        echo "Uploading notebooks from $LOCAL_NOTEBOOKS_PATH to $REMOTE_NOTEBOOK_PATH in the workspace $DATABRICKS_HOST"
        databricks workspace import_dir --overwrite "${LOCAL_NOTEBOOKS_PATH}" "${REMOTE_NOTEBOOK_PATH}" --debug
      shell: bash
      env:
        DATABRICKS_HOST: ${{ inputs.databricks-host }}
        DATABRICKS_TOKEN: ${{ inputs.dtabricks-token}}
        LOCAL_NOTEBOOKS_PATH: ${{ inputs.local-path }}
        REMOTE_NOTEBOOK_PATH: ${{ inputs.remote-path }}
